
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CardData : Luban.BeanBase
{
    public CardData(JSONNode _buf) 
    {
        { if(!_buf["CardType"].IsNumber) { throw new SerializationException(); }  CardType = (CardType)_buf["CardType"].AsInt; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
    }

    public static CardData DeserializeCardData(JSONNode _buf)
    {
        return new CardData(_buf);
    }

    public readonly CardType CardType;
    public readonly string Name;
   
    public const int __ID__ = 55917306;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "CardType:" + CardType + ","
        + "Name:" + Name + ","
        + "}";
    }
}

}

