
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum GameDataType
    {
        Gold = 0,
        Food = 1,
        Wood = 2,
        Stone = 3,
        Iron = 4,
        Technology = 5,
    }

} 

