
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class GameData : Luban.BeanBase
{
    public GameData(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = (GameDataType)_buf["Id"].AsInt; }
        { if(!_buf["InitData"].IsNumber) { throw new SerializationException(); }  InitData = _buf["InitData"]; }
    }

    public static GameData DeserializeGameData(JSONNode _buf)
    {
        return new GameData(_buf);
    }

    public readonly GameDataType Id;
    public readonly int InitData;
   
    public const int __ID__ = -1704998180;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "InitData:" + InitData + ","
        + "}";
    }
}

}

