
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum GroundType
    {
        None = 0,
        House = 1,
        Food = 2,
        Gold = 3,
        Wood = 4,
        Stone = 5,
        Iron = 6,
        Technology = 7,
        Center = 8,
        Weapons = 9,
    }

} 

