
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class LV1Ground : Luban.BeanBase
{
    public LV1Ground(JSONNode _buf) 
    {
        { if(!_buf["GroundType"].IsNumber) { throw new SerializationException(); }  GroundType = (GroundType)_buf["GroundType"].AsInt; }
        { if(!_buf["Path"].IsString) { throw new SerializationException(); }  Path = _buf["Path"]; }
    }

    public static LV1Ground DeserializeLV1Ground(JSONNode _buf)
    {
        return new LV1Ground(_buf);
    }

    public readonly GroundType GroundType;
    public readonly string Path;
   
    public const int __ID__ = -1985338290;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "GroundType:" + GroundType + ","
        + "Path:" + Path + ","
        + "}";
    }
}

}

