
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbGameData TbGameData {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbGameData = new TbGameData(loader("tbgamedata"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbGameData.ResolveRef(this);
    }
}

}
