
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbCardData TbCardData {get; }
    public TbGameData TbGameData {get; }
    public TbLV1Ground TbLV1Ground {get; }
    public TbLV2Ground TbLV2Ground {get; }
    public TbLV3Ground TbLV3Ground {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbCardData = new TbCardData(loader("tbcarddata"));
        TbGameData = new TbGameData(loader("tbgamedata"));
        TbLV1Ground = new TbLV1Ground(loader("tblv1ground"));
        TbLV2Ground = new TbLV2Ground(loader("tblv2ground"));
        TbLV3Ground = new TbLV3Ground(loader("tblv3ground"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCardData.ResolveRef(this);
        TbGameData.ResolveRef(this);
        TbLV1Ground.ResolveRef(this);
        TbLV2Ground.ResolveRef(this);
        TbLV3Ground.ResolveRef(this);
    }
}

}
