
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbCardData
{
    private readonly System.Collections.Generic.Dictionary<CardType, CardData> _dataMap;
    private readonly System.Collections.Generic.List<CardData> _dataList;
    
    public TbCardData(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<CardType, CardData>();
        _dataList = new System.Collections.Generic.List<CardData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CardData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = CardData.DeserializeCardData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.CardType, _v);
        }
    }

    public System.Collections.Generic.Dictionary<CardType, CardData> DataMap => _dataMap;
    public System.Collections.Generic.List<CardData> DataList => _dataList;

    public CardData GetOrDefault(CardType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CardData Get(CardType key) => _dataMap[key];
    public CardData this[CardType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

