
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbLV3Ground
{
    private readonly System.Collections.Generic.Dictionary<GroundType, LV3Ground> _dataMap;
    private readonly System.Collections.Generic.List<LV3Ground> _dataList;
    
    public TbLV3Ground(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<GroundType, LV3Ground>();
        _dataList = new System.Collections.Generic.List<LV3Ground>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            LV3Ground _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = LV3Ground.DeserializeLV3Ground(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.GroundType, _v);
        }
    }

    public System.Collections.Generic.Dictionary<GroundType, LV3Ground> DataMap => _dataMap;
    public System.Collections.Generic.List<LV3Ground> DataList => _dataList;

    public LV3Ground GetOrDefault(GroundType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public LV3Ground Get(GroundType key) => _dataMap[key];
    public LV3Ground this[GroundType key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

